export const fontStyles = {
     'SourceSansPro-Regular': require('../assets/fonts/source-sans-pro/SourceSansPro-Regular.ttf'),
     'SourceSansPro-Black': require('../assets/fonts/source-sans-pro/SourceSansPro-Black.ttf'),
     'SourceSansPro-BlackItalic': require('../assets/fonts/source-sans-pro/SourceSansPro-BlackItalic.ttf'),
     'SourceSansPro-Bold': require('../assets/fonts/source-sans-pro/SourceSansPro-Bold.ttf'),
     'SourceSansPro-BoldItalic': require('../assets/fonts/source-sans-pro/SourceSansPro-BoldItalic.ttf'),
     'SourceSansPro-ExtraLight': require('../assets/fonts/source-sans-pro/SourceSansPro-ExtraLight.ttf'),
     'SourceSansPro-ExtraLightItalic': require('../assets/fonts/source-sans-pro/SourceSansPro-ExtraLightItalic.ttf'),
     'SourceSansPro-Italic': require('../assets/fonts/source-sans-pro/SourceSansPro-Italic.ttf'),
     'SourceSansPro-Light': require('../assets/fonts/source-sans-pro/SourceSansPro-Light.ttf'),
     'SourceSansPro-LightItalic': require('../assets/fonts/source-sans-pro/SourceSansPro-LightItalic.ttf'),
     'SourceSansPro-Semibold': require('../assets/fonts/source-sans-pro/SourceSansPro-Semibold.ttf'),
     'SourceSansPro-SemiboldItalic': require('../assets/fonts/source-sans-pro/SourceSansPro-SemiboldItalic.ttf'),
     'Montserrat-Black':require('../assets/fonts/Montserrat/static/Montserrat-Black.ttf'),
     'Montserrat-BlackItalic': require('../assets/fonts/Montserrat/static/Montserrat-BlackItalic.ttf'),
     'Montserrat-Bold':require('../assets/fonts/Montserrat/static/Montserrat-Bold.ttf'), 
     'Montserrat-BoldItalic':require('../assets/fonts/Montserrat/static/Montserrat-BoldItalic.ttf'),
     'Montserrat-Medium':require('../assets/fonts/Montserrat/static/Montserrat-Medium.ttf'), 
     'Montserrat-MediumItalic':require('../assets/fonts/Montserrat/static/Montserrat-MediumItalic.ttf'), 
     'Montserrat-Regular':require('../assets/fonts/Montserrat/static/Montserrat-Regular.ttf'),
     'Montserrat-SemiBold':require('../assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf'),
}